### ISSUE TITLE
Notes are duplicated in Bass and Treble Clef

### ISSUE THREAD

**Issue by wmedrano** [blairjordan/pianoboi#6]
Is this intended behavior?
Would it be feasible to merge the clefs so that they share middle C?

**Comment by blairjordan** [comment]
@wmedrano Probably not intended by design, more likely laziness (just feeding keys into vexflow).

I don't see an issue with merging them off the top of my head, so I'll have a play around with this.

Thinking out loud, bass stave just needs to be raised, split keys array into two (between B/C) and feed these to treble/bass separately. Treble clef size would need to be reduced also. Possibly more to it but I can give it a try.

**Comment by blairjordan** [comment]
Commit 9b3bccf resolves this issue.
